epi_params: {
    # Figure 1 and 3 
    'E2_S1_b':{
        'vax_scenario' : 'age_structure',
        'current_immunity': 0,
        'vaccination_type': 'VDE',
        'R0s':[2],
        'stop':2000,
        't0': 0,
        'g1': 0.6 
        },

    'E2_S2_b':{
        'vax_scenario' : 'age_structure',
        'current_immunity': 0,
        'vaccination_type': 'VDE',
        'R0s':[2],
        'stop': 2500,
        't0': 440,
        'g1': 0.6 
        },

    
    # Figure 5
    'E2_2w':{ # 2nd - wave like
        'vax_scenario' : 'age_structure',
        't0': 0, 
        'current_immunity': 0.2,  #0.04,
        'R0s':[2.7], 
        'vaccination_type': 'VDE',
        'stop': 2000,
        'g1': 0.6 #0.45
        }, 

    'E2_4w':{ # 4th - wave like
        'vax_scenario' : 'age_structure',
        't0': 220, 
        'current_immunity':  0.4, #0.1,  # in case of Gab ses = structure
        'R0s':[3], # 
        'vaccination_type': 'VDE',
        'stop': 2000,
        'g1': 0.6 #0.4
    }
}



matrix_params: {
    # true data scenarios
    'Ma': {'sim_type': 'mazsk','nw' : '12'},
    'Mb': {'sim_type': 'mazsk','nw' : '19'},

    'C0': {'sim_type': 'synthetic','nw' : 'sy'}, #age_polymod

    'M7': { #scenario from preavious paper
        'country':  Hungary,
        'sim_type': 'synthetic',
        'dist_Pd2' : [0.35, 0.45, 0.20],
        'mixing_type': 'assortative_mixing',
        'r'  :  [0.60, 0.5, 0.65] ,
        'ds' : [0.6, 0.6, 0.5],
        'activity': [0.2, 0.4, 0.4],
        'nw' : 'sy' 
        },

}

npi_params: {
    'delta_C': {
        'NPI': 0.8,
        'rel': 1.2},

    '4':{ 
        'mixing_type': 'assortative_mixing',
        'day_npi': 65,
        'r'  : [0.5, 0.6, 0.7] , 
        'ds' : [0.5, 0.4, 0.4] , 
        'activity':[0.4, 0.25, 0.35]}, 
    
    }
        

    